[package]
name = "ross"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]

[dependencies]
lalrpop-util = "0.13.1"
regex = "0.2.5"
failure = "0.1.1"
itertools = "0.7.6"
matches = "0.1.6"

[build-dependencies]
lalrpop = "0.13.1"
